/**
 *
 * $Id$
 */
package jointPackage_BibTeX2DocBook.validation;

import jointPackage_BibTeX2DocBook.SrcMasterThesis;
import jointPackage_BibTeX2DocBook.TrgDocBook;

/**
 * A sample validator interface for {@link jointPackage_BibTeX2DocBook.JointMM}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JointMMValidator {
	boolean validate();

	boolean validateSourceRoot(SrcMasterThesis value);
	boolean validateTargetRoot(TrgDocBook value);
}
