/**
 *
 * $Id$
 */
package jointPackage_BibTeX2DocBook.validation;

import jointPackage_BibTeX2DocBook.TrgBook;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link jointPackage_BibTeX2DocBook.TrgDocBook}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TrgDocBookValidator {
	boolean validate();

	boolean validateBooks(EList<TrgBook> value);
}
