/**
 *
 * $Id$
 */
package jointPackage_BibTeX2DocBook.validation;

import jointPackage_BibTeX2DocBook.TrgSection;

/**
 * A sample validator interface for {@link jointPackage_BibTeX2DocBook.TrgPara}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TrgParaValidator {
	boolean validate();

	boolean validateContent(String value);
	boolean validateSection(TrgSection value);
}
