/**
 *
 * $Id$
 */
package jointPackage_Ecore2Maude.validation;

import jointPackage_Ecore2Maude.SrcEAttribute;
import jointPackage_Ecore2Maude.SrcEClass;
import jointPackage_Ecore2Maude.SrcEOperation;
import jointPackage_Ecore2Maude.SrcEReference;
import jointPackage_Ecore2Maude.SrcEStructuralFeature;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link jointPackage_Ecore2Maude.SrcEClass}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SrcEClassValidator {
	boolean validate();

	boolean validateAbstract(boolean value);
	boolean validateInterface(boolean value);
	boolean validateESuperTypes(EList<SrcEClass> value);
	boolean validateEOperations(EList<SrcEOperation> value);
	boolean validateEAllAttributes(EList<SrcEAttribute> value);
	boolean validateEAllReferences(EList<SrcEReference> value);
	boolean validateEReferences(EList<SrcEReference> value);
	boolean validateEAttributes(EList<SrcEAttribute> value);
	boolean validateEAllContainments(EList<SrcEReference> value);
	boolean validateEAllOperations(EList<SrcEOperation> value);
	boolean validateEAllStructuralFeatures(EList<SrcEStructuralFeature> value);
	boolean validateEAllSuperTypes(EList<SrcEClass> value);
	boolean validateEIDAttribute(SrcEAttribute value);
	boolean validateEStructuralFeatures(EList<SrcEStructuralFeature> value);
}
