/**
 *
 * $Id$
 */
package jointPackage_Ecore2Maude.validation;

import jointPackage_Ecore2Maude.SrcEAttribute;
import jointPackage_Ecore2Maude.SrcEClass;
import jointPackage_Ecore2Maude.SrcEReference;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link jointPackage_Ecore2Maude.SrcEReference}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SrcEReferenceValidator {
	boolean validate();

	boolean validateContainment(boolean value);
	boolean validateContainer(boolean value);
	boolean validateResolveProxies(boolean value);
	boolean validateEOpposite(SrcEReference value);
	boolean validateEReferenceType(SrcEClass value);
	boolean validateEKeys(EList<SrcEAttribute> value);
}
