/**
 *
 * $Id$
 */
package jointPackage_Ecore2Maude.validation;

import jointPackage_Ecore2Maude.SrcEClass;

/**
 * A sample validator interface for {@link jointPackage_Ecore2Maude.SrcEStructuralFeature}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SrcEStructuralFeatureValidator {
	boolean validate();

	boolean validateChangeable(boolean value);
	boolean validateVolatile(boolean value);
	boolean validateTransient(boolean value);
	boolean validateDefaultValueLiteral(String value);
	boolean validateUnsettable(boolean value);
	boolean validateDerived(boolean value);
	boolean validateEContainingClass(SrcEClass value);
}
