/**
 *
 * $Id$
 */
package jointPackage_Ecore2Maude.validation;


/**
 * A sample validator interface for {@link jointPackage_Ecore2Maude.TrgConstant}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TrgConstantValidator {
	boolean validate();

	boolean validateOp(String value);
}
