/**
 *
 * $Id$
 */
package jointPackage_Ecore2Maude.validation;

import jointPackage_Ecore2Maude.TrgModule;
import jointPackage_Ecore2Maude.TrgTheory;

/**
 * A sample validator interface for {@link jointPackage_Ecore2Maude.TrgModElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TrgModElementValidator {
	boolean validate();

	boolean validateModule(TrgModule value);
	boolean validateTheory(TrgTheory value);
}
