/**
 *
 * $Id$
 */
package jointPackage_Ecore2Maude.validation;

import jointPackage_Ecore2Maude.TrgModExpression;
import jointPackage_Ecore2Maude.TrgRenMapping;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link jointPackage_Ecore2Maude.TrgRenModExp}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TrgRenModExpValidator {
	boolean validate();

	boolean validateModExp(TrgModExpression value);
	boolean validateRenamings(EList<TrgRenMapping> value);
}
