/**
 *
 * $Id$
 */
package jointPackage_UML2ER.validation;

import jointPackage_UML2ER.SrcClass;

/**
 * A sample validator interface for {@link jointPackage_UML2ER.SrcProperty}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SrcPropertyValidator {
	boolean validate();

	boolean validatePrimitiveType(String value);
	boolean validateComplexType(SrcClass value);
	boolean validateIsContainment(boolean value);
}
