/**
 *
 * $Id$
 */
package jointPackage_CPL2SPL.validation;

import jointPackage_CPL2SPL.SrcBusy;
import jointPackage_CPL2SPL.SrcDefault;
import jointPackage_CPL2SPL.SrcFailure;
import jointPackage_CPL2SPL.SrcNoAnswer;
import jointPackage_CPL2SPL.SrcRedirection;

/**
 * A sample validator interface for {@link jointPackage_CPL2SPL.SrcProxy}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SrcProxyValidator {
	boolean validate();

	boolean validateTimeout(String value);
	boolean validateRecurse(String value);
	boolean validateOrdering(String value);
	boolean validateBusy(SrcBusy value);
	boolean validateNoAnswer(SrcNoAnswer value);
	boolean validateRedirection(SrcRedirection value);
	boolean validateFailure(SrcFailure value);
	boolean validateDefault(SrcDefault value);
}
