/**
 *
 * $Id$
 */
package jointPackage_CPL2SPL.validation;


/**
 * A sample validator interface for {@link jointPackage_CPL2SPL.SrcSwitchedPriority}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SrcSwitchedPriorityValidator {
	boolean validate();

	boolean validateLess(String value);
	boolean validateGreater(String value);
	boolean validateEqual(String value);
}
