/**
 *
 * $Id$
 */
package jointPackage_CPL2SPL.validation;

import jointPackage_CPL2SPL.TrgExpression;
import jointPackage_CPL2SPL.TrgStatement;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link jointPackage_CPL2SPL.TrgForeachStat}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TrgForeachStatValidator {
	boolean validate();

	boolean validateIteratorName(String value);
	boolean validateSequenceExp(TrgExpression value);
	boolean validateStatements(EList<TrgStatement> value);
}
