/**
 *
 * $Id$
 */
package jointPackage_CPL2SPL.validation;

import jointPackage_CPL2SPL.Direction;
import jointPackage_CPL2SPL.TrgArgument;
import jointPackage_CPL2SPL.TrgBranch;
import jointPackage_CPL2SPL.TrgMethodName;
import jointPackage_CPL2SPL.TrgStatement;
import jointPackage_CPL2SPL.TrgTypeExpression;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link jointPackage_CPL2SPL.TrgMethod}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TrgMethodValidator {
	boolean validate();

	boolean validateType(TrgTypeExpression value);
	boolean validateDirection(Direction value);
	boolean validateMethodName(TrgMethodName value);
	boolean validateArguments(EList<TrgArgument> value);
	boolean validateStatements(EList<TrgStatement> value);
	boolean validateBranches(EList<TrgBranch> value);
}
